sudo: required
language: minimal
services:
- docker
script:
- echo "${DOCKER_PASSWORD}" | docker login --username gruen --password-stdin
- make lint
- make build
- make test
- make push
env:
  global:
    secure: yap3AIus2MqjLmEE96NVyGB3h/X0Nl7nLIt0g2v5vKDqjqbcu1946U1wcgThXWxxKX7fvDQPcrFxyeT/VwONfGHa27RyZcINyJxc3oMZERN59u1k6kAofwQ/DphIfXYwgiSyTmWyarIzZaVQEZP2YTW5dBZWJDJc2RDFgWJSxxyd7tcbSSqmD/X0L3j2Nt0isjAZq/AwdzZ5Clvw98oslXyGw1rUTnxfioXCLr6BbjXKV8BSibiQZt37C/pxcZJEMDKpuR8tOkgYyz3yY7dqGiuYWx6S76Ybp3Emr3D8IsnQZUpYrQMwPCtQneAuKNgKSAiyE4w36Fb2xT2aRH92nCkncdpA0UU+V+i+2hjBKW8BcCbG7xRxa7wes/uJjkFqhaXanzlWZoNGdbxyrV/f3WZjyqKnfjCIyrGUdjl/1UHmP9RsTZVq861StD3/UDJ00UGAvSeDLTxptHc0PflsTVBV/xmcgC8Mh0W2Ur4fx88CQRuQzfZ/EyPvLij8+tCt1PQLsokW2LZFo0CAG78I7BE6Dj4xN9Ima1aPANTnN5eQkKSPkN5f0hPAh1NmiPQs10ONF5OoeYXGrXOZaKynEEG5y8MG1v4Xs/VaetFDefRj75hHlooOKSPpWX/JDVdenTfXGDEZIIM5JL2zTb/G2bpSvbryVyn2gMhXkZtdv5M=
