sudo: required
language: minimal
services:
- docker
script:
- echo "${DOCKER_PASSWORD}" | docker login --username "${DOCkER_USERNAME}" --password-stdin
- make lint
- make build
- make test
- make push
env:
  global:
  - secure: GBbi01mkYFs9pFBbWozL6O9CGRbCMt9fBgkJRXyHeSYEELVQlmpu1SQIFPZbskvKpVZcZVz2+c9yARP+RAXLgeWAJnz8Mkgmu0AzvTeoZn1F436Qlrqgc2dpxKiu10xz78/s4JnBzvmwDLMwblbLnoPa6A4FIv4jwu0M4u03lrvSji2mEDaiI8H/cR9cKkKNejjx+rVPatr0Vl/RpKF8hql8uCuSlCpLYuFkVSAb93jZ9lPP5REv0reQWV2MvgA9huTIICqb/oqXTV6d5qDFxITNckbskEqcVBKCE5q458JuvIiFy4JYdMhv0ny+Ipz1xOrH3HUTTTRAkfHtSCOTtCB4h2vPVQmnuFtH06vEJepc4RMvAh050knwluTqdiXiKoegW3N+zG7FB7ir7tXM9MvbeugCnQSiUwE2ZIdQv2jDilpwqDkZKOuTX2KaRAhkzmWiE29x9JxTF23jeS8sx9S9mxHPj9P5R8tvS1ImRv22DvZnJyR4u3vFFli+yUROcsIML98iPOpxpr5ZLrwdLXkp1cRgcA9UUnzGZE/lFUi1xDR9D8zu07cIflE4AA5aLpp5sEmIPdXeN+UhnYhCcDaMMI6i7aJQZT6U3o52N3KqFx+U591RhjP/fMZvCCZgZTGDkHOL3kIc/a5eyZWNzPMo/D/R+DaAjgxH6eSJJhw=
  - secure: ZesoceX7Qyw8dbnkEFRexa9VgIjMPYbOtY+cAiX4eQOvfKn1TPc6B0RCAYy36sIFyalAF6G9gaWUHk9Ti6h6pn9l3/T3BhLRkhaDfXt09Rpamz2CeITKEOOyUHxWaKZ5dvD5Jr62umJjN8B5OuUlxbwhD0fS1Gst4A0rWm/I8Mv94yxRHSmumX/T8YmI6gDy6Oz0rgmZ0PqMTxszcnC0iAGmN2xlEgmBluC7qwaY2bWOErcnDjTCnPMoM72b4kBkoeHCCGH7bFKzdIJpZJ1kFoIV4dR+7IenjvQLUpu9Dc9tQmqfOcOphTie2TAI/7BWRxQMXBetjwW5f/daXksg8uKfBL1bJvEArcNgKnAcffcslafP+FlaM6TOp1Tr4eTXrb0vnyBihoo0o3Y5K/sORSnJ5+6YQXno2oeKPmOQWe+3xF4w9GrI1S/wPiBeRTplvbpXDJsGSKX+l8iKQTJqc9st9uK+7XR5+3GXPNGj53pYDXWfBrjSEQrFsRMDv5CzjtcJgEQ+wcxAOf+UTswn75fmg+gMrroMnfgqnVdS+YFi9zLURYUFbm+woQPen/wNdPjEzBtH+G8H51HDWYM7QeA5s1tYWXj936DuOYx0HHgwVomgNm1OreMcaT1/hpGw3qFDlicMEVuTrXQPoENSPlx5eUuwfugnR7SeD9J22RY=
