sudo: required

language: minimal

services:
  - docker

script:
  - docker login --username ${DOCkER_USERNAME} --password-stdin <<< ${DOCKER_PASSWORD}
  - make lint
  - make build
  - make test
  - make push
