sudo: required
language: minimal
services:
- docker
script:
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCkER_USERNAME} -p
- make lint
- make build
- make test
- make push
env:
  global:
  - secure: t0RqPdTW8xYZzxyPfX9IrXu7yOKqliufZCmxg5OJYBDjY9boXAAzwvFoCEBuh6snc//IEDkT4pJAUxPpsUgYOTJwsFzG3x8b4EneJY3Dgds0Eo2Aw4WtQFutMw9byJN3DN4O5kmxVvYyhG2PLidQf9U2/KJJeXCdG6EgxTrGk1H/LYgv8Y22VsRaKM6Xm7vGufhfF1huLSUSFIrgB6zo5Tv8Ou7a+5bEINRN+crH8SHdWpipEb/rMfzhh2r8mHr3PBKaC/z2xeYtrDb+WZlLfvnRaLvnrqiZhA4Uymga7Y1QP/OZ+3DkpATPVOJ3cQwneMepBEpJTqAzo2ELjj0gvZVpQmNGmEEGTkgGR+rckuFFSbJxyF75MJhiRjKuMjtft4WLEYFDEEnLGaJGKOlbfFvx+rRKJ215MFI9B9bWF6pdDaMRQJPy1KfhdeJBdgf2WkRVSDk+FkND9wCbc3y2aNGK7ZS9Jegyd1Q1nutBx6fAlYvViVvhN0ZgYb1Eg+i4zetRQSjVYWjHh5ONlcIhV09BrfQFv0Vkh83RYQKCcJShof9TGUfqotHc81ePCh8s9Jgh+X0edk23G8LMvKuQr0oXZSP5brZCVHbrcBYrrsyYOM43xrRTsQRjJz8ee4UXYh1eGKAhaAJnH17QlklUwWRlqYoYrf2xM706makrLnU=
  - secure: dOuWyr4l/70TYZrI0sguu+nBP+orCo3bOKC1EwMvqe8ng6pCq/mOmXlWpG1l8d1FH7bLgKj9yNzW8YyzNKYdiUQEYI/a3oxM8PkGrILOK1iM0ykKUOY3+z8F4TV2kq3I2xkVQUNE9Wu9Rb3VYzWy26HbWk9mgLds3znBVEc/dJYnECkg5Pi2Kqej7Sa+kTAFInbPSK4plmVvb0fX3/7jNzdWMxYgXGTL/XYfV4c+ZYJU0UYi568JtXrTR9PsifRchdn5xM82QORs0NamMGNSgzerlKDbZJFxsLeR29UFg365d81v6VMa820Fn/kChnXSz4IfUQZcGuSBV7wBAlbwA+hGL++ANp0RSV5pPXViAFRzFPLczFPFsfXJ3hVwI/gW7QPj9O+q6k7JoI91Ok2/Ow590K9lspLJnTtBxQ+RMFfdVUo76JSYDgBRpCkjV6Tswvcgsx3eTIujP65gZxDNafeACR0QBUMVweHpo3eUfBnKCELqMMJBMlf79OUwyM3lIiFFzRB+uJTFhsHuPPvFOVWQZdOhbFkcn3HRPwrom+qLzViIsPKG1auSnmaeF5krlIa80Y9s+ScuVtFLefKBNLxJ2ONAZHGRj4gBQf4DwzI0CjNmD3shTE0umlESMUP/xjOpBVlyd697mJVNeOeePUF9c9bDRu126bK/1GQPPXg=
