sudo: required
language: minimal
services:
- docker
script:
- docker login -u ${DOCkER_USERNAME} --password-stdin <<< ${DOCKER_PASSWORD}
- make lint
- make build
- make test
- make push
env:
  global:
  - secure: 0LYyTvgJmFehlT25iJA5vVcp91YrJF6ldidlEKRkbz//fzPB7MJlsViYgar/a2DYhd8v9OvbHYYiflVO5BPhaeZ9M7o6TZ/NbuMUK+crYGma61Io3pFiDYqj4smmXOoT0p44qbYyI3gy0LOJvsby/DyVIVZmrlEXCw6XBjbIsXyWa04MYx9GWZ4g3ZG7lpU4v1Yz9FHdtZJnPxNR2SH+1ZgsbnTNJUpr56lizwAETodXna0wS+8sTp2YtaYotfu+i9MeixefOQDhBZboqX/QfXdZon3isK9yaazE0zhv2McF5/am/CJlMTelovSbJb2y68M5u7Q2bJT4uS9ZBfy9Fu/qpC7mMpl0xGPuQvZrABXW036mAhfi80E8APZiuI6xgDXdLwmYfc10Mikhfx0pqMHoH9E6SF+LKhq6IUo8dU+O9rNMn8tCdBu9P+J7khxiKd5UTWrqGzAVO1moPhpcCKHHYs+ISOr9xWZD1HwM9NdcMUsJQT02S9XTMXKcZw+8ArUVLxNpiPzEVEbgAHPkJVz72RHVDxdP1p2sKcdKZqvXcFVRhO7L3E66qcGshxNB3+J/40Ca6/M4Ljcc4BknV5RbZRtUEdLduQnDbCdh2V08W092O7K5hUpR26WD4l64vXaT675QXF3alOX4YWgtA0xjgHOMLOBCvCegloWXAUU=
  - secure: Ho6j4MhDWtsdReMDdziqHjpZN50Vr4fAJFOnH6kYq1+WBzS2A2NcJL29qStxLoagu+kQLNmazRgK33QD5sHdjpg5bg51vE7wlJjJWtRGcc2izHUJsGjQTrCNIyePRhNuHFGEIB0UjcK37yP4JhNTWBod8e8Du5N40olpjTVch3c5NumwCp2JRjjWyOiRIIr1sbrAyXNim0svaxI32gMH1iJmsmJ4zr/rIFXCJgwbn6XrEpgCsaWHZpt9MVP4crxFwJ74JduGoA6y21UEBpAf3/bRbPgwi9/YS0zRZUhAYuTIX4fWUUFRD243eI11GnX8AaW9Avie1lCPs8fZ9XFdzfyx1KkzXs9QhV4a0wqem8cn99j0Zx0C1R1kgiRQXlSHr2g/wjk2aJpdO2uGbza8kNzMFoIzx0bl4BfvFfUg/3O/luWPl6TQ6V7FdggQIMYgku+rXEtCQz8sVMr4vc4wt7/G80RuWMHz2JFfVwzDbU4JXKMVI71ZOlrODCHu2rLXzRhLMd5ANR+j4WUOrhAzmlxYIWk9LDVaEfv+KS2zqWPh6+pqorBgzQsAREjcBS4pHazHhBKW8KpSx9og+bddqAoVgTYWeiQ9eBifs9fkqSyei4g6nRVXafxlmf6OMgrSLzk5a0uY+5nIh4yJ6k4c0W0tGevTeNSTPz4w6xd8paQ=
