sudo: required
language: minimal
services:
- docker
script:
- docker login -u "${DOCkER_USERNAME}" -p "${DOCKER_PASSWORD}"
- make lint
- make build
- make test
- make push
env:
  global:
  - secure: jPRYtoms1jhFp/b9ZxBP/4MTxHX0B5HGsE5jdMvNB/eKEaHGVKvtTUsCLXXdvh+DqSloUiiNlu8C+sjKEfUXK9cTb7Dc3T8UqNpFEWjNSoGUSIyvyeoi8+L+gYv77nHoLW/jmISD06PzGdNgyRtCQ7aUsk5SZBdqwkcD7tjicrtcdTMlhKLWTt5bgN8MTtnuLmI9QqxDpeiB/QrpFhSN7QjjXg+L0QRQsnxq4/dAObIQkVr5+JiDCI4e0SKC8zdWPHa48zfV1tnP8r5SO1BLYI0rcBA0Nmtr3IyPCR/cO7GiPG/9+SFQWPhF+Wm0ZFQ7vFefs6kXrixQeysJrL8s/WvveKdvxuab0f1hXXVrHwJA8jGlDYi5UtEYy0FFdtZCxhhStIHVeVqegLWelfDuWxuUYk3g4SYuOk+seE9mjQuz1X0w4R39q2rtCYOV4OcNqJXv6ZbTu2IJta0ZDasjPJ6QRyV4er/mUGSxqQ26wwZ9T0G34SsdPkpFV6gxtFrDlfCE6ZWZGIMxXMIsXgXJZUFoclKtfVlvrBLQlYL0qrQrheo7KHHUKuAYDm9PW/hb2n/aJnO2SHhvgoxr92HqDNs4WW9mI5lDsqj6/9fXrGy7qz8LNJRtm2EJnUos2s1n1E4ehl3mfjU2raDmSDOXH80JrzMDobVOkRvfpBzQOis=
  - secure: PYejanLE3fQEx5S3tYaZkzHt0MwFDrwmVuXR3vpvnAGxxGtfvQLZtoE1J/fs/3SaLqwFw9MZ8sWDrBRG/CxLQUT95nDaLVuMb5t3vTsitPYnZW3+kSjwbk73/wvGvjIMQczODUmE7eaVUp4Sp+QvSljVqOAGpo5lf2dxa63oMmMToEIT10FvDLWV02J8eBqpPs2R9ZMA8+UYRmKmOqAtMZJw/tj3ZjQgfbjU9bLTwVP/p2oRFwRkK7+BlBL71B1nMXQDgvzqQjCL/3cln5wy8YflyVHSZR/XVWWr4UM6bawIygRrvnutos8WgMnKX5nucyU4FRt40c8LmMlxdf04rdFQcObMSpfdLRgHIqx/zCId/laB8rUYfqDkSuHc8rHN4V0QQOY4ExATsNIAPeTEzC2UQQShkGnJ7jy7PD1VM7TisSnoxxj1lvuQDxMBmuUOmI8aRXbmSvKUKzYL+pDeBoOswZ2+3/uhYDBe4ij9/ueRd6+tHUD1uZQr5eZpTV/aWy0E76rZz21fJYi0pJeTVzcDw67/yJziN0C16X7IHXNjeV/upz9CxNsP2c/nZIAfrGzGV0DmW8MKnPHt2z+OKmh/5aUytaIQQZVX7t6MgTcQTPqSGs1FobkKi12yXxoAct9Tmnk8AZU7J7L9ZaxaYdp9pOxV5Je+r0YosSfcyr8=
